### ISSUE TITLE
Add reversed versions of enter and backspace symbols

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-keymanweb-osk#1]
Add mirror-image reversed versions of two symbols:

source, sourceencoding, newname, newencoding
enter, E005, enterrev, E071
back, E004, backrev, E072

**Comment by jvgaultney** [comment]
IOW reversed versions of these:

![image](https://user-images.githubusercontent.com/4226750/95608619-4d481680-0a55-11eb-8682-af14ea630ef8.png)

**Comment by mcdurdin** [comment]
Is it possible to add at the same time, versions of these shift symbols with a line underneath:

![image](https://user-images.githubusercontent.com/4498365/95642998-019a7900-0af8-11eb-9c45-9a80e7edb6e5.png)

Something like:

![image](https://user-images.githubusercontent.com/4498365/95643005-0828f080-0af8-11eb-987d-be5004da118f.png)

These represent Caps Lock

**Comment by mcdurdin** [comment]
The reversed versions of enter and back are correct, yes. (I note the font has space in a lower range, e.g. E00C-E00F, that we could fill up neatly).

**Comment by jvgaultney** [comment]
Thanks. Yes I'll add the Caps Lock ones too.

**Comment by jvgaultney** [comment]
Done. [See v2.100](https://github.com/silnrsi/font-keymanweb-osk/releases/tag/v2.100).

**Comment by mcdurdin** [comment]
Thank you Victor!
