### ISSUE TITLE
Add ZWNJ symbol

### ISSUE THREAD

**Issue by darcywong00** [silnrsi/font-keymanweb-osk#2]
Sorry I didn't catch this earlier.

If we end up implementing keymanapp/keyman#2738 for Keyman 14.0, we'll also need to add this to the font.

@rmlockwood points out iOS and Android use different symbols. Maybe worth a discussion with @mcdurdin when the time comes.

**Comment by jvgaultney** [comment]
Happy to add it when you decide what it should look like. It would be possible to put two symbols in the font at two different code points, and Keyman could choose which to use for display based on OS.

**Comment by mcdurdin** [comment]
I think having both symbols is good -- we may leave it up to the keyboard developer to select a symbol rather than putting OS-specific switching in.

**Comment by jvgaultney** [comment]
I'll add both as soon as you provide samples of what they should look like.

**Comment by mcdurdin** [comment]
<img width="367" alt="Draft" src="https://user-images.githubusercontent.com/7088137/75338889-ca8c9580-588f-11ea-86b5-d6e7137afeb9.png">

![Persian Gboard Layout](https://user-images.githubusercontent.com/7088137/75338904-ceb8b300-588f-11ea-80bd-528f366e94b7.png)

In both cases, the key to the right of the space bar

**Comment by jvgaultney** [comment]
Thanks!

**Comment by jvgaultney** [comment]
Done - release 2.200:

https://github.com/silnrsi/font-keymanweb-osk/releases/tag/v2.200
