### ISSUE TITLE
Additional non-printing symbols

### ISSUE THREAD

**Issue by mcdurdin** [silnrsi/font-keymanweb-osk#3]
There are a few other non-printing symbols which are in use in Keyman keyboards for which it would be good to have representations. I don't yet have samples, so this is just noting for when we have time to source and/or design good symbols:

* ZWSP
* ZWJ
* NBSP
* WJ
* LRM, RLM
* The various other spacing chars
* Mongolian Vowel Separator?
* Others? **TODO**

**Comment by jvgaultney** [comment]
For control characters that have no glyph shape we have in the past used symbols like these:

![image](https://user-images.githubusercontent.com/4226750/151320811-3a9b14ee-4fea-4526-b31d-719d8715b940.png)

There is a six letter limit on what we can place in the square. Any more than the letters get too small to read. 

By 'other spacing chars' do you mean the variety of spaces used in publishing? Here's a list of what we support in our Latin-script fonts:

00A0 NO-BREAK SPACE
2007 FIGURE SPACE
2008 PUNCTUATION SPACE
2003 EM SPACE
2002 EN SPACE 
2000 EN QUAD
2001 EM QUAD
2004 THREE-PER-EM SPACE
2005 FOUR-PER-EM SPACE
2006 SIX-PER-EM SPACE
2009 THIN SPACE
200A HAIR SPACE
202F NARROW NO-BREAK SPACE

We could create these in the same sway - with dotted square and letters. 

If this design works for you we can add the ones you specify and add more later.

**Comment by mcdurdin** [comment]
This is certainly good as a starting point. I think that there are some other symbols that some platforms use for certain marks, but I haven't had the time to research this yet.

**Comment by jvgaultney** [comment]
Is this still needed? How soon? And are there other symbols you need?

**Comment by mcdurdin** [comment]
This has been back-burner for us and no immediate urgency, but for completeness with the LDML keyboard work I would like to try and get these in for our Keyman 17.0 release due in September.

I think the set that you've listed, along with ZWSP, ZWJ, NBSP, WJ, LRM, RLM would be ideal.

Thanks!

**Comment by jvgaultney** [comment]
Thanks - that's helpful. I'll assume that something like the design above is sufficient.

**Comment by mcdurdin** [comment]
> I'll assume that something like the design above is sufficient.

Yes thanks!

**Comment by mcdurdin** [comment]
I think we have the characters we need for now. No one is crying out for the others. Thanks!
